namespace: 'youpayroll'

app_name: 'youpayroll'

job:
  name: 'youpayroll-migration-job'
  backoffLimit: 0
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 30
  serviceAccountName: 'ygag-youpayroll-vault'

  containers:
    - name: 'migration'
      imagePullPolicy: 'Always'
      image: '459037613883.dkr.ecr.me-central-1.amazonaws.com/production/ygg/youpayroll/backend-app:[BUILD_TAG]'
      command: '["sh", "-c", "source /vault/secrets/application.env ; source /vault/secrets/application-devops.env ; python3.11 manage.py migrate --noinput >> /ygag/logs/app.out.migration.log 2>&1"]'
      memory:
        requests: 1000Mi
        limits: 1500Mi
      cpu:
        requests: 1000m
        limits: 1500m
      volumeMounts:
        - mountPath: '/ygag/logs/'
          name: 'ygag-youpayroll-sandbox-migration-logs'
        - name: 'youpayroll-app-env-volume'
          mountPath: "/vault/secrets"

  volumes:
    - name: 'ygag-youpayroll-sandbox-migration-logs'
      hostPath:
        path: '/home/ec2-user/ygag-logs/ygag-youpayroll-sandbox/migration'
    - name: 'youpayroll-app-env-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "youpayroll-envs"
    
    

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'default'
  priorityClassName: 'sandbox-critical'
  restartPolicy: 'Never'
  terminationGracePeriodSeconds: 120
