SecretProviderClass:
- name: youpayroll-envs
  namespace: youpayroll
  provider: vault
  parameters:
    roleName: "ygg-eks-youpayroll-app-role"
    objects: |
      - objectName: "application.env"
        secretPath: "ygag-secrets/data/it/sandbox/youpayroll/env-uae"
        secretKey: "app-env"
      - objectName: "application-devops.env"
        secretPath: "ygag-secrets/data/devops/sandbox/external/it/youpayroll/env-uae"
        secretKey: "app-env"
