namespace: 'youpayroll'

app_name: 'youpayroll'
environment: 'sandbox'
type: 'consumer-name'

service:
  name: 'youpayroll-consumer-name'
  default:
    port: 8000
    protocol: 'TCP'
    targetPort: 8000

hpa:
  name: 'youpayroll-consumer-name-hpa'
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

pdb:
  name: 'youpayroll-consumer-name-pdb'
  minAvailable: 50%

deployment:
  name: 'youpayroll-consumer-name-deployment'
  replicas: 1
  maxSurge: 100%
  maxUnavailable: 0%
  serviceAccountName: 'ygag-youpayroll-vault'

  containers:
    default:
      name: 'consumer-name'
      imagePullPolicy: 'Always'
      image: '459037613883.dkr.ecr.me-central-1.amazonaws.com/production/ygg/youpayroll/backend-app:[BUILD_TAG]'
      command: '["sh", "-c", "source /vault/secrets/application.env ; source /vault/secrets/application-devops.env ; python3.11 manage.py consumer >> /ygag/logs/app.out.consumer-name.log 2>&1"]'
      memory:
        requests: 300Mi
        limits: 400Mi
      cpu:
        requests: 150m
      volumeMounts:
        - mountPath: '/ygag/logs/'
          name: 'ygag-youpayroll-sandbox-consumer-name-logs'
        - name: 'youpayroll-app-env-volume'
          mountPath: "/vault/secrets"


  volumes:
    - name: 'ygag-youpayroll-sandbox-consumer-name-logs'
      hostPath:
        path: '/home/ec2-user/ygag-logs/ygag-youpayroll-sandbox/consumer'
    - name: 'youpayroll-app-env-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "youpayroll-envs"

    
    

  nodeSelector:
    key: 'karpenter.sh/provisioner-name'
    value: 'default'

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: 'topology.kubernetes.io/zone'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'youpayroll'
          tier: consumer-name

  priorityClassName: 'sandbox-medium'
  terminationGracePeriodSeconds: 60
