SecretProviderClass:
- name: youpayroll-envs
  namespace: youpayroll-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-youpayroll-app-role"
    objects: |
      - objectName: "application.env"
        secretPath: "ygag-secrets/data/it/qa/youpayroll/env-uae"
        secretKey: "app-env"
      - objectName: "application-devops.env"
        secretPath: "ygag-secrets/data/devops/qa/external/it/youpayroll/env-uae"
        secretKey: "app-env"
