namespace: 'youpayroll-[JIRA_ID]'

app_name: 'youpayroll-[JIRA_ID]'
environment: 'qa'

service:
  name: 'youpayroll-[JIRA_ID]-redis'
  default:
    port: 6379
    protocol: 'TCP'
    targetPort: 6379

enableHPA: false
hpa:
  name: 'youpayroll-[JIRA_ID]-redis-hpa'
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

enableKedaCron: true
keda:
  name: 'youpayroll-[JIRA_ID]-redis-keda'
  minReplicas: 0
  desiredReplicas: 1
  maxReplicas: 1
  start: "0 7 * * 1-5"
  end: "0 22 * * 1-5"
  cpu: 80

pdb:
  name: 'youpayroll-[JIRA_ID]-redis-pdb'
  minAvailable: 100%

deployment:
  name: 'youpayroll-[JIRA_ID]-redis-deployment'
  replicas: 1
  maxSurge: 100%
  maxUnavailable: 0

  containers:
    default:
      name: 'redis'
      imagePullPolicy: 'IfNotPresent'
      image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/redis:6.2.4'
      command: '[]'
      port: 6379
      memory:
        requests: 20Mi
        limits: 500Mi
      cpu:
        requests: 10m
        limits: 300m

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'database'
  priorityClassName: 'qa-medium'
  terminationGracePeriodSeconds: 60

