namespace: 'youpayroll-[JIRA_ID]'

pvc:
  - name: 'youpayroll-[JIRA_ID]-ebs-database'
    accessModes:
      - 'ReadWriteOnce'
    resources:
      requests:
        storage: 1Gi
    storageClassName: 'ebs-sc'

