namespace: 'youpayroll-[JIRA_ID]'

app_name: 'youpayroll-[JIRA_ID]'
environment: 'qa'

service:
  name: 'youpayroll-[JIRA_ID]-worker'
  default:
    port: 8000
    protocol: 'TCP'
    targetPort: 8000

enableHPA: false
hpa:
  name: 'youpayroll-[JIRA_ID]-worker-hpa'
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

enableKedaCron: true
keda:
  name: 'youpayroll-[JIRA_ID]-worker-keda'
  minReplicas: 0
  desiredReplicas: 1
  maxReplicas: 1
  start: "0 7 * * 1-5"
  end: "0 22 * * 1-5"
  cpu: 80

pdb:
  name: 'youpayroll-[JIRA_ID]-worker-pdb'
  minAvailable: 50%

deployment:
  name: 'youpayroll-[JIRA_ID]-worker-deployment'
  replicas: 1
  maxSurge: 100%
  maxUnavailable: 0%
  serviceAccountName: 'ygag-youpayroll-vault'

  containers:
    default:
      name: 'worker'
      imagePullPolicy: 'IfNotPresent'
      image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/ygg/youpayroll/backend-app:[BUILD_TAG]'
      command: '["sh", "-c", "/bin/cat /vault/secrets/application.env /vault/secrets/application-devops.env > /etc/profile.d/application-env.sh ; sed -i \"s/\\[JIRA_ID\\]/[JIRA_ID]/g\" /etc/profile.d/application-env.sh ; source /etc/profile.d/application-env.sh ; sh /ygag/deployment/app/worker-entrypoint.sh"]'
      memory:
        requests: 300Mi
        limits: 400Mi
      cpu:
        requests: 10m
      volumeMounts:
        - mountPath: '/ygag/logs/'
          name: 'ygag-youpayroll-[JIRA_ID]-qa-worker-logs'
        - name: 'youpayroll-app-env-volume'
          mountPath: "/vault/secrets"


  volumes:
    - name: 'ygag-youpayroll-[JIRA_ID]-qa-worker-logs'
      hostPath:
        path: '/home/ec2-user/ygag-logs/ygag-youpayroll-[JIRA_ID]-qa/worker'
    - name: 'youpayroll-app-env-volume'
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "youpayroll-envs"
    
    

  initContainers:
    database:
      - image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/postgres:16.6'
        cmd: 'pg_isready -p 5432'
        host: 'youpayroll-[JIRA_ID]-database'
        name: 'init-database'
    redis:
      - image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/redis:6.2.4'
        host: 'youpayroll-[JIRA_ID]-redis'
        name: 'init-redis'

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'default'

  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: 'topology.kubernetes.io/zone'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'youpayroll-[JIRA_ID]'
          tier: worker
    - maxSkew: 2
      topologyKey: 'kubernetes.io/hostname'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'youpayroll-[JIRA_ID]'
          tier: worker

  priorityClassName: 'qa-medium'
  terminationGracePeriodSeconds: 60
