namespace:
  - name: 'youpayroll-[JIRA_ID]'
    annotations:
      field.cattle.io/projectId: 'c-m-mwl52l26:p-46vll'

    resource_quota_disabled:
      requests.cpu: "3340m"
      requests.memory: 6856Mi
      limits.memory: 10080Mi
